// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClmACXvg3n4P0OvBz1wDdg9WbqzWi6pEc',
    appId: '1:850392119685:web:d4b6e440fd328be0da6cec',
    messagingSenderId: '850392119685',
    projectId: 'chat-app-e91aa',
    authDomain: 'chat-app-e91aa.firebaseapp.com',
    storageBucket: 'chat-app-e91aa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb4Dim3dG_jTmr7AsqPsXiH-Sp8j6iL2Q',
    appId: '1:850392119685:android:2fc3d71cfce45f6ada6cec',
    messagingSenderId: '850392119685',
    projectId: 'chat-app-e91aa',
    storageBucket: 'chat-app-e91aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFZ6qUQT-iicG1ryyV5VtoUGlTF-wAIe8',
    appId: '1:850392119685:ios:dd512f8eab80fdb2da6cec',
    messagingSenderId: '850392119685',
    projectId: 'chat-app-e91aa',
    storageBucket: 'chat-app-e91aa.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFZ6qUQT-iicG1ryyV5VtoUGlTF-wAIe8',
    appId: '1:850392119685:ios:dd512f8eab80fdb2da6cec',
    messagingSenderId: '850392119685',
    projectId: 'chat-app-e91aa',
    storageBucket: 'chat-app-e91aa.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClmACXvg3n4P0OvBz1wDdg9WbqzWi6pEc',
    appId: '1:850392119685:web:dc704dd98f753565da6cec',
    messagingSenderId: '850392119685',
    projectId: 'chat-app-e91aa',
    authDomain: 'chat-app-e91aa.firebaseapp.com',
    storageBucket: 'chat-app-e91aa.firebasestorage.app',
  );
}
